### PR TITLE
Guard against element.tagName not being a string.

### LINKED ISSUE #2035: It does not work fine on codeforces.com.
The icon on the toolbar become gray. And on some webpages, such as [http://codeforces.com/problemset/problem/635/A](http://codeforces.com/problemset/problem/635/A), it doesn't work.
OS version:Windows 10 x64
Vimium Version:1.54

### PR DESCRIPTION
**Pull request by smblott-github**
Example page: http://codeforces.com/contest/752/problem/B; see #2035.

Here's what you get if you `console.log element.tagName`:

snapshot

There, `element.tagName` is an element with `name` `tagName` (not a string).  Here, we guard against that case.

Fixes #2035.

### CODE REVIEW

**Comment by philc** [comment]
Nice find and nice fix. How is that even possible?

File: content_scripts/link_hints.coffee [hunk 1]
```diff
@@ -626,7 +626,9 @@ LocalHints =
   # image), therefore we always return a array of element/rect pairs (which may also be a singleton or empty).
   #
   getVisibleClickable: (element) ->
-    tagName = element.tagName.toLowerCase()
+    # Get the tag name.  However, `element.tagName` can be an element (not a string, see #2305), so we guard
+    # against that.
+    tagName = element.tagName.toLowerCase?() ? ""
```
Comment (philc) [inline content_scripts/link_hints.coffee]: Minor: while yours is more succinct, I think this is more explicit:

```
# It's possible that element.tagName is an element, not a  string. See #2305.
tagName = if typeof(element.tagName) == "string" then element.tagName.toLowerCase() else ""
```
