### PR TITLE
avoid triggering popup blocker on some old versions of firefox 

### LINKED ISSUE #4165: Firefox can't open links in new windows
**Describe the bug**
When I press `F` to get hints that open in a new tab, they no longer open (from a couple of weeks ago, but the 1.67.3 release didn't fix this when it fixed other stuff). Typing `f` for hints and entering the hints in uppercase to get them in a new window also does nothing. Does seem to still work in Chrome though.

**To Reproduce**
0. Use Firefox with Vimium installed
1. Go to https://vimium.github.io/
2. Press `F`. Choose any link, this should open in a new browser tab.

Include a screenshot if applicable.

**Browser and Vimium version**

Firefox: 94.0
OS: Linux 5.14.18-100.fc33.x86_64 #1 SMP Fri Nov 12 17:38:44 UTC 2021
Vimium: 1.67.3

### PR DESCRIPTION
**Pull request by gdh1995**
The old code in #4000 ignores Firefox versions which are older than 96 while don't belong to 91. So this PR adds it.

Should fix #4165 .

### CODE REVIEW

**Comment by tim-goto** [comment]
To circumvent the issue that is being fixed by this PR I installed the latest version of the plugin locally and it does not have this issue besides the fact that this PR is not yet merged. Maybe I am running into something differently though..

File: lib/dom_utils.js [hunk 1]
```diff
@@ -323,7 +323,7 @@ var DomUtils = {
       // In firefox prior to 96, simulating a click on an element would be blocked. In 96+,
       // extensions can trigger native click listeners on elements. See #3985.
       const mayBeBlocked = event === "click" && Utils.isFirefox() && parseInt(Utils.firefoxVersion()) < 96
-          && /^91\.[0-5](\.|$)/.test(Utils.firefoxVersion())
+          && /^(?!91\.)|^91\.[0-5](\.|$)/.test(Utils.firefoxVersion())
```
Comment (philc) [inline lib/dom_utils.js:326]: This regexp is now pretty complicated to look at, and the comment doesn't indicate why we're checking for Firefox 91.

I think this would be much easier to work with if 1) we added firefoxMajorVersion and firefoxMinorVersion to Utils and used those for comparisons, so we don't have to use parseInt on a string and regexps to parse those out here, and 2) updated the comment to describe why we're checking against Firefox 91 in this section.

Comment (gdh1995) [reply lib/dom_utils.js]: Hello Philc, I've updated the code to make it clear.

**Comment by gdh1995** [comment]
And as I've updated in https://github.com/philc/vimium/pull/3985#issue-1101757110 , Firefox 91.6+ still reports "popup-blocked" on a plain `click` event on `<a target=_blank>`, so I also add a check in this commit to fix it.

Just now I tested the commit cb78fa5 on Firefox 90, 91.0esr, 91.6esr and 96, and it works perfectly whether Firefox's `Block pop-up windows` (aka. `dom.disable_open_during_load`) is enabled or not.

**Comment by philc** [comment]
Thanks @gdh1995
