### PR TITLE
fix broken copy, paste and showFindMode since Chrome 74

### LINKED ISSUE #3260: URL copy/paste and Find mode focus issues in latest Chrome builds
Derived from #2833 now that Chrome also seems to have received bizzare changes in this area. (mainly [this](https://github.com/philc/vimium/issues/2833#issuecomment-464462596) comment)
I have waited four Dev releases (once a week) to conclude these regressions are likely to stick, so contributors may want to examine them early before they eventually reach Stable.

There are at least three issues emerged together in Chrome 74:
1. When `Find` is initiated, the HUD gets no focus. You have to click in it to start inputting.
2. `yy` is broken, fails to copy anything, despite the HUD says it succeeded.
3. `p` sends empty string instead of the string/URL copied in clipboard, resulting in default search engine being opened with no query. 

3 is tricky to reproduce, it most likely to repro when you don't `p` immediately after copy a link, e.g. copy a link via `yf`, scroll around to read the rest of page, then `p`.
If you `p` right after `yf` without any operation in between, the pasting will succeed.

### LINKED ISSUE #3292: Find mode doesn't receive focus in brave
Hi, I've noticed in the last few weeks that when I try to use find mode (`/`) in Brave it doesn't actually receive focus automatically. If I want to use Vimium's find mode I have to manually select it with my mouse after it appears on the screen.

Brave build information:
Version 0.63.40 Chromium: 74.0.3729.61 (Official Build).

The same problem is occurring in both Windows and Linux. Chromium in both OSes still works fine.

Let me know if you need any other troubleshooting information.

### LINKED ISSUE #3297: [Chrome] yy not yanking current URL
Chrome Version: Version 74.0.3729.108 (Official Build) beta (64-bit)
OS Version: MacOS 10.14.4 (18E226)
Vimium Version: 1.64.5

A couple of days ago I noticed that `yy` does not seem to work anymore. I still get the little bottom-right toast saying the URL has been yanked, but CMD+v still pastes the old clipboard content.

Same behaviour in incognito mode.

### LINKED ISSUE #3298: [Chromium] / to search doesn't actually select the text box for you to type in
Chromium | 74.0.3729.108 (Official Build) Arch Linux (64-bit)
Vimium version 1.64.5

https://i.imgur.com/uyApM4Q.png <- this is what it looks like for me at the moment.
Intended behavior: Pressing / automatically selects the textbox so you can immediately start typing to find text.
Currently, it doesn't do this. If I try to type immediately after pressing /, nothing happens. The only way to make the search work properly is to click on the box after it comes up, which seems to defeat the purpose.

### LINKED ISSUE #3302: `/` search window not getting focus
Pressing `/` activates search, but it doesn't have the cursor's focus.
image
I have to click on it before I can start typing. Seems like it started happening when chrome updated to v74. 

Google Chrome 74.0.3729.108 (Official Build) (64-bit)
Revision: daaff52abef89988bf2a26091062160b1482b108-refs/branch-heads/3729@{#901}
OS: Mac OS X

Vimium Version
1.64.5

### LINKED ISSUE #3307: search mode stopped working
focus in search mode does not work
**Chrome:** 74.0.3729.108
**Vimium:**  1.64.5
**GIF:** 

I did not notice this before, I can press the key ```/```
and everything worked fine.
maybe something I am doing so?
Or new changes appeared in the browser.

### LINKED ISSUE #3311: Find mode is not focused by default
When I press `/` to enable find mode, the `/` feedback is displayed on the bottom of the page, however if I press any other key, nothing happens. However, if I first enter `yy` and then type `/`, the find text field is focused and then everything works as expected. I can also click on the find field, but we are using vimium because we do not want to touch the mouse after all.

I am using version 1.64.5 on Chrome 74 in Ubuntu 18.04.2 LTS. Any ideas how to fix this?

### LINKED ISSUE #3313: I can not input anything in find mode "/". It only works when open the help "?"
- Chrome version:  74.0.3729.131
- OS version: macOS Mojave 10.14.4
- Vimium version: 1.64.5

### LINKED ISSUE #3315: unable to input in find mode
I enter the find mode by pressing `/`, but I cannot input the keyword unless I click in the edit box with the mouse. Is that normal?

### PR DESCRIPTION
**Pull request by gdh1995**
During tests I found that a setTimeout is needed, ~~although I haven't found why~~.

This can fix #3260, fix #3292, fix #3297, fix #3298, fix #3302, fix #3307, fix #3311, fix #3313 and fix #3315 .

### CODE REVIEW

**Comment by gdh1995** [comment]
@smblott-github Would you like to merge this for just a try? There're quite a few issues reporting the new FindMode and clipboard issue on Chrome 74, and this PR works on my laptop and PC (both are Win 10 x64).

**Comment by riftEmber** [comment]
How did you divine the 17ms solution? (I haven't tested)

**Comment by gdh1995** [comment]
> How did you divine the 17ms solution? (I haven't tested)

I once thought it's the recently-added "user activation" logic (since Chrome 72) that prevents Vimium code from working. The "user activation" logic is designed to pass privileges across frames and remove them after a while. Therefore, **if it has bugs**, Chrome may mistakenly pass "disabled" status from a normal web page to Vimium's privileged frames, and then at a small time span code may fail.

So I tried adding a timeout and found the privilege came back. Recently, I noticed that "0ms" might be not enough, and "17ms" seems to work well - if not, we may increase it again.

But I navigated Chromium source code for minutes but didn't find any buggy source code. More survey is needed.

**Comment by gdh1995** [comment]
Update: after more tests, I find it's a race condition:

* the action of `element.focus()` / `select()` can work only if a document "**is**" visible
  * if a doc is not visible, `getSelection().selectAllChildren()` works but
  * the "visible selection" is none, and `getSelection() + ""` always returns `""` (an empty string).
* But in most time a HUD iframe has `vimiumUIComponentHidden` and its "display" is "none",
  * although Vimium code may call "toggleIframeElementClasses" for `paste`
  * it needs a tiny time span to spread the "display:block" style to the HUD frame.

Therefore, a `toggleIframeElementClasses` + `getComputedStyle` before `postMessage` can help a lot:
* should call `toggleIframeElementClasses` before all 3 HUD actions: showFind, copy, paste
* `getComputedStyle` is to enforce a style update immediately

But during tests in today there're about 1 / 10 cases where th HUD could not get focused, so I think the `setTimeout 17` is still necessary.

**Comment by innaterebel** [comment]
Let's also try tagging @philc to see if he will sort things out. (if tagging the project owner is even necessary for him to get notified...)

**Comment by gdh1995** [comment]
I've confirmed the comment I wrote above:
* Chrome 74 refuses Element.focus and Selection.toString in an iframe if the iframe is not visible
* Vimium's `iframePort` for HUD iframe is created by `MessageChannel`
  * it sends messages immediately when `postMessage` is called, and stack trace is:
  * https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/messaging/message_port.cc?dr=C&g=0&l=76
  * https://cs.chromium.org/chromium/src/mojo/public/cpp/bindings/lib/connector.cc?dr=C&g=0&l=315
* changes to `<iframe>.classList` posts a new task and Chrome does style updates in the task
  * the task is not executed until the JavaScript code finishes and the task manager continues its task loop.
  * during the task, some messages are sent from parent frame (a content page) to child frame (HUD)
  * the message channel is IPC
  * one message is `RenderWidget::OnWasShown` and stack trace on HUD is: 
    * `RenderWidget::OnWasShown` -> `RenderWidget::SetHidden` -> `LayerTreeView::SetVisible`
* then there's a **potential race condition** between `execCommand("Copy")` and `SetVisible`
  * in fact, usually `execCommand("Copy")` is eariler if only HUD has been inited
  * while before Chrome 74 a hidden frame of `display:none` can still copy text
    * making us ignore the race condition.

Here's the result of `chrome://tracing` using Vimium master (v1.64.5) on Chrome 74.0.3729.108 x64 (blank User Data, Win 10):

image

The result of this PR:

image

**Comment by mohitt** [comment]
Hi, all are we going to have build of this PR

**Comment by gdh1995** [comment]
@smblott-github Sorry to disturb you again, but there have been so many issues reporting FindMode focusing and copying problem on Chrome 74. Would you have time to merge this? This PR has been verified carefully.

**Comment by FUNNYDMAN** [comment]
Guys, please merge it if everything is okay because someone switched to the mouse again(

**Comment by athakral** [comment]
If someone is in dublin, Ireland. May be he can request him personally.

https://www.computing.dcu.ie/~sblott/

**Comment by megalithic** [comment]
@smblott-github friend; this is huge! would love to have this merged in, to further make this tool amazing again! thanks!

**Comment by elongl** [comment]
Why don't we merge this is it seems to work?
Also, isn't there a better solution than setting a timeout?

**Comment by adriangonzalez** [comment]
For anyone that's getting a little jumpy on this issue, it looks like a fix is coming, but in the meantime, cmd/ctrl+F still works ;)

**Comment by innaterebel** [comment]
Hate to break it to you guys, but do you know the word "abandoned"? That's where we indeterminately are.

While everybody is welcomed to make pull requests in an open source project, a project does have an owner and owner-approved committers, who are the only people possessing the privilege to **actually** merge a pull request and publish an official build.
For Vimium, the owner is @philc, and currently the only committer is @smblott-github. Unfortunately, both of them have been inactive for quite some time for reasons unknown, so the practically abandoned state we are in.

The abandonment is likely not intentional, but there is no guarantee the two will come back. If you are really bothered by the issues and cannot wait around it, you may want to find an alternative extension.

**Comment by gdh1995** [comment]
@mrmr1993 Sorry to disturb you but do you still has commiting permission to Vimium repo? I'd like this PR to be merged to fix Vimium's FindMode focus and clipboard operations issues, which occur on Chrome 74 and are quite annoying.

File: content_scripts/ui_component.coffee [hunk 1]
```diff
@@ -8,7 +8,10 @@ class UIComponent
 
   toggleIframeElementClasses: (removeClass, addClass) ->
     @iframeElement.classList.remove removeClass
-    @iframeElement.classList.add addClass
+    unless @iframeElement.classList.contains addClass
+      @iframeElement.classList.add addClass
+      if addClass == "vimiumUIComponentVisible"
+        getComputedStyle(@iframeElement).display
```
Comment (mrmr1993) [inline content_scripts/ui_component.coffee]: Pretty sure this is a no-op, and the value doesn't seem to be used at any of the callsites. Is this needed?

**Comment by mrmr1993** [comment]
@gdh1995 never had commit permissions. I left a query comment on the code, but nothing I can do on actually merging, sorry.

File: content_scripts/ui_component.coffee (hunk 1 above)
Comment (gdh1995) [reply content_scripts/ui_component.coffee]: No, it's not a no-op. `getComputedStyle` will force Chrome to execute a "layout" operation during the calling, and then its inner code can find HUD becomes visible and then send a "child-frame-become-visible" message to the HUD process (i.e. Vimium process). Only when the message is received, Chrome's renderer will accept `element.focus` / `selection.toString()` commands from JavaScript.

A much more detailed tracing has been mentioned in https://github.com/philc/vimium/pull/3277#issuecomment-487363284

Comment (mrmr1993) [reply content_scripts/ui_component.coffee]: Okay, makes sense. Might be worth adding a comment to that effect, since it's not obvious from the code alone.

Comment (gdh1995) [reply content_scripts/ui_component.coffee]: Thanks for tips. Added.

**Comment by ssangervasi** [comment]
innaterebel was a bit sassy, but it is likely the maintainers have lost interest. The good thing about open source is that we can fork it and even release a fork to the extension store. In fact, [gdh1995 has a fork/rewrite](https://github.com/gdh1995/vimium-c). I appreciate their efforts to fix the original project, and I'm curious how stable Vimium-C is.

**Comment by gdh1995** [comment]
not as stable as Vimium; not all functions have been merged. And, unfortunately, it was unpublished by Google yesterday, because of unsuitable description/snapshot. I'll try to complain in these days.


 
---Original---

**Comment by elongl** [comment]
@innaterebel 
So why doesn't someone else fork the project and just basically take ownership of it?
Someone who actually cares about Vimium.

**Comment by doingnothing** [comment]
Could you help me? 
Failed to load extension
File
~/Downloads/vimium-fix-focus-of-hud
Error
Could not load background script 'lib/utils.js'.
Could not load manifest.

**Comment by gdh1995** [comment]
[vimium_1.64.5-merge-3277.zip](https://github.com/philc/vimium/files/3166098/vimium_1.64.5.zip)

@doingnothing This is my compiled version of this PR.

If you want to use Vimium from source code, then you need to "compile" Vimium, and you need to install Node.js, CoffeeScript, and run `cake build`. Refer: https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#installing-from-source

**Comment by doingnothing** [comment]
> [vimium_1.64.5-merge-3277.zip](https://github.com/philc/vimium/files/3166098/vimium_1.64.5.zip)
> 
> @doingnothing This is my compiled version of this PR.
> 
> If you want to use Vimium from source code, then you need to "compile" Vimium, and you need to install Node.js, CoffeeScript, and run `cake build`. Refer: https://github.com/philc/vimium/blob/master/CONTRIBUTING.md#installing-from-source

I just found your extension on Chrome Web Store.
https://chrome.google.com/webstore/detail/vimium-c/hfjbmagddngcpeloejdejnfgbamkjaeg?hl=en-US
And successfully installed it.
It seems to work perfectly.
Thank you very much!

**Comment by elongl** [comment]
@gdh1995 
Should I replace my Vimium with your Vimium C?
Would you keep maintaining it?

**Comment by gdh1995** [comment]
only a few features like across-frame hints, filtered hints, and search word completion are no in Vimium C. So, if you don't use them, you may replace vimium with vimium c.


I'll continue to develop and maintain vimium c for at least 2 more years, and if no accidents, for a decade ^_^.


 
---Original---

**Comment by innaterebel** [comment]
> So why doesn't someone else fork the project and just basically take ownership of it?

So why did you ask this when there has always been one and is mentioned in this thread (and many other places in this issue tracker)...
> Someone who actually cares about Vimium.

Don't get me wrong, I fully appreciate all developers who has been participated in this project for their honorably wasting of their time. I was not complaining about them for anything.
I am not a native speaker, not familiar with the actual impression and extra nuance a word may imply to the native speaker, some unintentional strong words may be used. I may sound sarcastic or something, if any, is not toward the developers.
I just wanted to explain the actually long-standing circumstance as more and more people could not see it.

It is less than obvious to people who are new to Vimium (moreover, new to this repository pages), but the developing power of Vimium is in fact currently in its lowest, since just before Firefox officially dropped the support of their versatile legacy add-ons, which introduced a whole lot of demand to the simplism Vimium.
With the departure of the last contributors, and the remain only committer apparently ran out his time or motivation to do major updates to the project. In the past couple months the only thing that was gain is the kind and helpful gdh1995.

I filed this focus/copy issue one month before it reached the stable version of Chrome, worrying the only committer would go completely offline anytime soon (the owner has been almost offline for years), but it was still too late.
It's a pity the developers gone without saying hi, but that's about it, the nature of open source volunteering, again not blaming any of them. We don't know any fact about their missing after all. The only thing we can know though a few clicks in this repository is the stressful demand to the project. If you cannot see it, this is the story.

**Comment by philc** [comment]
Hey folks, bandwidth from the committers is low at the moment, but not zero. Rest assured we'll get this fix into the chrome store release soon. Stephen or I will follow up on this issue in the next 48 hours.

File: pages/hud.coffee [hunk 2]
```diff
@@ -86,7 +86,7 @@ handlers =
     countElement.id = "hud-match-count"
     countElement.style.float = "right"
     hud.appendChild countElement
-    Utils.setTimeout 0, -> inputElement.focus()
+    Utils.setTimeout 17, -> inputElement.focus()
```
Comment (philc) [inline pages/hud.coffee]: Why 17ms -- because that's the duration of 1 frame at 60 fps? Let's move this value into a variable constant (e.g. FRAME_DURATION) with a description explaining why it's 17ms.

**Comment by athakral** [comment]
Ye ye he is back :)

File: pages/hud.coffee (hunk 2 above)
Comment (gdh1995) [reply pages/hud.coffee]: Firstly, thanks.

During my tests on Chrome 74.0.3729.108 x64, Win10, with blank user data folder, a 0~1ms timeout was not enough. Although the success rate then seemed >= 90%, I could still reproduce the fails every a few retries.

It is indeed because 17ms is a frame interval that I choose it. The ideas behind it are: 1. the time span should be long enough for operating system's message receiving (IPC) race conditions; 2. not so long that users may feel it. Therefore, I think any time span among 10ms~50ms may be OKay. And during the further tens of retries, 17ms worked well.

BTW, maybe the failing of 1ms is because my PC was doing other heavy work like video playing / code compiling - an operating system may be busy in other tasks, and it does need some time to wake up a process / thread, so 1ms is not so safe for inter-process communications.

I'll extract it to a constant.

**Comment by philc** [comment]
@gdh1995 great work on this. This problem was tricky and the fix is thoroughly researched and explained. I'll merge and cut a new release.

**Comment by philc** [comment]
This is now on the chrome store  as v1.64.6 and should roll out in the next few hours.

**Comment by adriangonzalez** [comment]
/ is working for find, but is n-Next and p-Previous doesn't seem to work for me?

**Comment by adriangonzalez** [comment]
Working now.

**Comment by gdh1995** [comment]
For who are interested in the browser code behind, here's what I find in the source code of Chromium:

https://github.com/gdh1995/vimium-c/blob/419e0c3067606f32f94779326de60f84ddbbf507/types/vimium_c.d.ts#L784-L801
