### PR TITLE
Fix visual indicator for `focusInput()`.

### LINKED ISSUE #1257: focusInput command overlays incorrect for off-screen inputs
The `focusInput` command (`gi`) shows input indicators in the wrong position if the page has to scroll to the input we focus.

screenshot from 2014-11-22 15 35 55
screenshot from 2014-11-22 15 36 23

### PR DESCRIPTION
**Pull request by smblott-github**
Currently, if an input is only partially in the view port, then the page may scroll when it is focused and the overlays for `focusInput()` are wonky.  See #1257.

Here, we draw the overlay around the *entire* input, instead of just around the visible part.  Being partially visible therefore is no longer relevant.

@mrmr1993... Does this look correct to you?

Fixes #1257.
Closes #1258.

### CODE REVIEW

File: lib/dom_utils.coffee [hunk 1]
```diff
@@ -116,6 +116,18 @@ DomUtils =
     null
 
   #
+  # Returns the smallest rectangle which encloses element.  Assumes that there is at least one rectangle.
```
Comment (mrmr1993) [inline lib/dom_utils.coffee]: Isn't this exactly what `element.getBoundingClientRects` does already?

Comment (smblott-github) [inline lib/dom_utils.coffee]: Thanks, @mrmr1993. I didn't know that existed.
